### PR TITLE
Add first ATL06 support.

### LINKED ISSUE #13: granules = find(:ICESat2, "ATL08") returns Any[]
Trying to get oriented with this package, I'd like to use if to work with ICESat-2 ATL06 data... running the first example returns a empty without error:

```
julia> granules = find(:ICESat2, "ATL08")
Any[]
```

Any idea what might be going on here?

### PR DESCRIPTION
**Pull request by evetion**
Fixes #13 
@alex-s-gardner

```julia
julia> using SpaceLiDAR
julia> fn = "~/Downloads/ATL06_20220404104324_01881512_005_01.h5"
julia> g = SpaceLiDAR.granule_from_file(fn)
SpaceLiDAR.ICESat2_Granule{:ATL06}("ATL06_20220404104324_01881512_005_01.h5", "/Users/evetion/Downloads/ATL06_20220404104324_01881512_005_01.h5", (x_min = 0.0,), (type = :ATL06, date = Dates.DateTime("2022-04-04T10:43:24"), rgt = 188, cycle = 15, segment = 12, version = 5, revision = 1, ascending = true, descending = false))
julia> df = reduce(vcat, DataFrame.(points(g)))
203776×10 DataFrame
    Row │ x         y         z          u           t                        q     track   power   trackid  reference
        │ Float64   Float64   Float32    Float32     DateTime                 Int8  String  String  Int8     Float32
────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────
      1 │ -105.221  -79.0058  1752.19    0.0111486   2022-04-04T10:43:41.664     0  gt1l    strong        1  1752.18
      2 │ -105.221  -79.0056  1752.23    0.0122074   2022-04-04T10:43:41.667     0  gt1l    strong        1  1752.17
      3 │ -105.221  -79.0054  1752.24    0.0111412   2022-04-04T10:43:41.669     0  gt1l    strong        1  1752.17
      4 │ -105.222  -79.0052  1752.19    0.00908957  2022-04-04T10:43:41.672     0  gt1l    strong        1  1752.17
      5 │ -105.222  -79.0051  1752.16    0.00937234  2022-04-04T10:43:41.675     0  gt1l    strong        1  1752.18
      6 │ -105.222  -79.0049  1752.16    0.00966735  2022-04-04T10:43:41.678     0  gt1l    strong        1  1752.19
      7 │ -105.222  -79.0047  1752.16    0.00983945  2022-04-04T10:43:41.681     0  gt1l    strong        1  1752.2
```

The `time_coverage_start` is in the granule filename, `g.date` in the above example. ~`atlas_spot_number` is not directly available, but `points(g)` gives you 6 tracks in order so it could be enumerated. I'm not sure why you need the number, but the beam strength is already provided in the above example.~

### CODE REVIEW

**Comment by alex-s-gardner** [comment]
@evetion this is fantastic! 

So the `spot` number is fixed relative to the satellite (the` spot` indicated the detector). The `beam` is fixed relative to the direction of flight (fixed position on the ground). To limit wear on any one side of the spacecraft the satellite rotated such that the spots associated with each beam switch. So if there is an issue with a specific detector it can only be traced with the `spot`

**Comment by alex-s-gardner** [comment]
@evetion as for the `time_coverage_start` I was adding this to the `delta_time` to get an exact date-time. Does the file name have the same precision as the `time_coverage_start`? I found that a precise time made it easier to locate relevant detect photons in the ATL03 product. Admittedly I'm probably digging deeper into the data than most users are interested in.

**Comment by evetion** [comment]
> So the spot number is fixed relative to the satellite (the spot indicates the detector)

Ok, I've added it as `trackid` in the above table example output.

> as for the time_coverage_start I was adding this to the delta_time to get an exact date-time.

I already calculate the exact datetime (`t` in the above table) by using a gps_offset and the `ancillary_data/atlas_sdp_gps_epoch` field. Could you confirm you get the same results with your method?

**Comment by alex-s-gardner** [comment]
@evetion yes, `land_ice_segments/delta_time` + `ancillary_data/atlas_sdp_gps_epoch` gives precise GPS seconds (seconds since 1980-01-06T00:00:00)... I should have looked at your code before requesting `time_coverage_start`

As for making the trackid == spot, I think that could be confusing as `track` refers to the ground tack and the `spot` refers to the detector which switches tracks when the spacecraft is rotated. If you don't want to add any additional fields I would suggest setting the trackid back to the track #. I can always hack things on my end to get the `spot` if adding fields is an issue

**Comment by evetion** [comment]
I'm open to adding/changing/removing fields. I was already considering not using XYZ, but lat, lon and elevation, just to be more clear. We can always make a breaking release.

I understand that `track` can be confusing, but so is `spot` for me. I do like to keep naming consistent, when feasible, over data products and missions. It seems GEDI uses `channel` to indicate the laser source. We could also use `beamid`? Which would have your preference?

**Comment by alex-s-gardner** [comment]
I think we should steer clear of `beam` or `track` as those names already have a meaning that contradicts the meaning of `spot`. For the ICESat2 sensor each detector has multiple `channels` which would also make things a bit confusing. What about `detectorid`

an I like the idea of changing `x/y` to `lat/lon`, `Z` to `height` - as it's the height above ellipsoid- or `elevation` and `t` to `datetime`. `u` could also be changed to `height_sigma`, maybe place `_` before id (e.g. `detector_id`), and `reference` could be changed to `height_ref`.

That's probably WAY more input than you wanted... either way the utility is fantastic

**Comment by alex-s-gardner** [comment]
Maybe we can also include the `land_ice_segments/ATL06_quality_summary` as `quality_flag`

**Comment by evetion** [comment]
```julia
help?> points(g)
  points(g::ICESat2_Granule{:ATL06})

  Retrieve the points for a given ATL06 (Land Ice) granule as a list of namedtuples, one for each beam. The names of the tuples are based on the following fields:

            Column                                   Field                                       Description
  –––––––––––––––– ––––––––––––––––––––––––––––––––––––––– –––––––––––––––––––––––––––––––––––––––––––––––––
         longitude             land_ice_segments/longitude        Longitude of segment center, WGS84, East=+
          latitude              land_ice_segments/latitude        Latitude of segment center, WGS84, North=+
            height                  land_ice_segments/h_li                  Standard land-ice segment height
      height_error           land_ice_segments/sigma_geo_h                  Total vertical geolocation error
          datetime            land_ice_segments/delta_time + ancillary_data/atlas_sdp_gps_epoch + gps_offset
           quality land_ice_segments/atl06_quality_summary   Boolean flag indicating the best-quality subset
             track                      gt1l - gt3r groups                                                 -
             power                                       -                    "strong" or "weak" laser power
       detector_id             atlas_spot_number attribute                                                 -
  height_reference             land_ice_segments/dem/dem_h                Height of the (best available) DEM

  You can combine the output in a DataFrame with reduce(vcat, DataFrame.(points(g))).
```
```julia
julia> reduce(vcat, DataFrame.(points(g)))
203776×10 DataFrame
    Row │ longitude  latitude  height     height_uncertainty  datetime                 quality  track   power   detector_id  height_reference
        │ Float64    Float64   Float32    Float32             DateTime                 Bool     String  String  Int8         Float32
────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      1 │  -105.221  -79.0058  1752.19              0.181907  2022-04-04T10:43:41.664     true  gt1l    strong            1         1752.18
      2 │  -105.221  -79.0056  1752.23              0.180661  2022-04-04T10:43:41.667     true  gt1l    strong            1         1752.17
      3 │  -105.221  -79.0054  1752.24              0.180411  2022-04-04T10:43:41.669     true  gt1l    strong            1         1752.17
      4 │  -105.222  -79.0052  1752.19              0.181494  2022-04-04T10:43:41.672     true  gt1l    strong            1         1752.17
      5 │  -105.222  -79.0051  1752.16              0.181617  2022-04-04T10:43:41.675     true  gt1l    strong            1         1752.18
      6 │  -105.222  -79.0049  1752.16              0.181003  2022-04-04T10:43:41.678     true  gt1l    strong            1         1752.19
      7 │  -105.222  -79.0047  1752.16              0.180741  2022-04-04T10:43:41.681     true  gt1l    strong            1         1752.2
      8 │  -105.222  -79.0045  1752.17              0.179844  2022-04-04T10:43:41.684     true  gt1l    strong            1         1752.21
```

Notable changes, apart from your suggestions:
- `quality` has become a boolean, with inverse (!) meaning of the flag in the source. `true` indicates that this is a good measurement.
- `height_error` is now based on the same field (was `u` and based on `h_li_sigma`)

**Comment by alex-s-gardner** [comment]
If we want to reduce data volume:
`power::String` could be changed to `strong_beam::Bool`
`track::String` could be changed to `track_id::Int8` where `tack_id` ranges from 1:6 and maps to `gt1l – gt3r` 

Otherwise this looks great and you should merge.

Did you want to do something similar for ICESat's GLAH06? I can also take a crack at it.

**Comment by alex-s-gardner** [comment]
> height_error is now based on the sigma_geo_h field (was u(uncertainty) and based on h_li_sigma)
Discussing with the project I think the best estimate of `height_error is sqrt(sigma_geo_h.^2 + h_li_sigma.^2)`

**Comment by evetion** [comment]
Thanks for providing a good estimate of `height_error`!

> If we want to reduce data volume
I'm on the fence here, as I like the readability of it as well. Maybe an `enum` would be best for both? Drawback is that most packages can't write a table with a `Vector{<:Enum}`. I've proposed a PR that would fix that in the future: https://github.com/yeesian/ArchGDAL.jl/pull/324.

Note that the output of `points` uses FillArrays, so the repeated track and power strings don't take much space at all. This advantage disappears when the output is `vcat`ted to a `DataFrame`.

> ICESat's GLAH06? I can also take a crack at it.
Feel free to take a crack at it, the functions are straightforward. You can start with the existing GLAH14 code. It helps to have a granule open in Panoply or similar to quickly detect the right fields. For writing the tests, I've uploaded a GLAH06 file here: `https://github.com/evetion/SpaceLiDAR-artifacts/releases/download/v0.1.0/GLAH06_634_2131_002_0084_4_01_0001.H5`, that you can use in the testsuite.

**Comment by alex-s-gardner** [comment]
Awesome!
The only thing you might still want to consider changing:
`power::String could be changed to strong_beam::Bool`

It's a more compact notation and `power `could become confused with the ATLAS laser beam energy level (laser power) that is increased as the laser degrades.

**Comment by alex-s-gardner** [comment]
Once you merge this pull request I'll take a crack at adding support for GLAH06

**Pull request merged**
